language: python
matrix:
  include:
    - name: "Linux Python 3.6"
      python: '3.6'
    - name: "Linux Python 3.7"
      python: '3.7'
    - name: "Linux Python 3.8 dev"
      python: '3.8-dev'
    - name: "Linux Python pypy"
      python: 'pypy3'
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - python3 --version
  - python3 -m pip install --upgrade pip
  - pip3 install -r requirements-nogpu.txt 
  - pip3 install --upgrade pytest
script: python3 -m pytest /tests/unit_tests.py
